# Site settings
title: Aaron J. Molstad
email: amolstad at umn dot edu
# description: 
url: "http://ajmolstad.github.io" # the base hostname & protocol for your site
# twitter_username: ajmolstad
# github_username:  ajmolstad

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
jobtitle: "Assistant Professor"
excerpt_separator: "<!--more-->"
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""